site_name: BIDS Extension Proposal Docs

theme: material

plugins:
  - search

docs_dir: docs

nav:
  - About: index.md
  - Guide: guide.md
  - Submission Process: submission.md
  - The Schema: schema.md

theme:
    name: material
    favicon: assets/favicon/favicon.ico
    logo: assets/img/logo.png
    features:
      - navigation.sections

markdown_extensions:
    - toc:
        anchorlink: true
    - pymdownx.superfences
