---
site_name: BIDS Extension Proposals
repo_url: https://github.com/bids-standard/bids-extensions/

plugins:
  - search
  - redirects:
      redirect_maps:
        "index.md": https://bids-website.readthedocs.io/en/latest/extensions/index.html
        "guide.md": https://bids-website.readthedocs.io/en/latest/extensions/specific-guidelines.html
        "submission.md": https://bids-website.readthedocs.io/en/latest/extensions/submission.html
        "schema.md": https://bids-website.readthedocs.io/en/latest/standards/schema/index.html
        "how-the-schema-works.md": https://bids-website.readthedocs.io/en/latest/standards/schema/how-the-schema-works.html
        "schema_objects.md": https://bids-website.readthedocs.io/en/latest/standards/schema/schema-objects.html
        "schema_rules.md": https://bids-website.readthedocs.io/en/latest/standards/schema/schema-rules.html
        "schema_meta.md": https://bids-website.readthedocs.io/en/latest/standards/schema/schema-meta.html
        "general_guidelines.md": https://bids-website.readthedocs.io/en/latest/extensions/general-guidelines.html
        "faq.md": https://bids-website.readthedocs.io/en/latest/faq/bids-extensions.html

docs_dir: docs

nav:
  - About: index.md
  - Guide: guide.md
  - Submission Process: submission.md
  - The Schema and Validator:
      - About the Schema: schema.md
      - Parts of the Schema: how-the-schema-works.md
      - Schema Objects: schema_objects.md
      - Schema Rules: schema_rules.md
      - Schema Meta: schema_meta.md
  - General Guidelines: general_guidelines.md
  - FAQ: faq.md

theme:
  name: material
  custom_dir: docs/overrides # - allows use of the overrides/main.html file
  favicon: assets/favicon/favicon.ico
  logo: assets/img/logo.png
  features:
    - navigation.sections
    - content.action.edit
    - announce.dismiss # allows for closing banner
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
  palette:
    - media: (prefers-color-scheme)
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

edit_uri: https://github.com/bids-standard/bids-extensions/edit/main/docs/

markdown_extensions:
  - toc:
      anchorlink: true
  - pymdownx.superfences
  - pymdownx.details
  - admonition
