site_name: BIDS Extension Proposals

theme: material

plugins:
  - search

docs_dir: docs

nav:
  - About: index.md
  - Guide: guide.md
  - Submission Process: submission.md
  - The Schema: 
      - About the Schema: schema.md
      - How the Schema Works: how-the-schema-works.md

theme:
    name: material
    favicon: assets/favicon/favicon.ico
    logo: assets/img/logo.png
    features:
      - navigation.sections

markdown_extensions:
    - toc:
        anchorlink: true
    - pymdownx.superfences
    - pymdownx.details
    - admonition
